name: Build APK

on:
  push:
    branches:
      - main  # أو الفرع الذي تريد بناءه

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Install Android SDK
      run: |
        sudo apt-get update
        sudo apt-get install -y lib32stdc++6 lib32z1
        wget https://dl.google.com/android/repository/commandlinetools-linux-6609375_latest.zip
        mkdir -p $ANDROID_HOME/cmdline-tools
        unzip commandlinetools-linux-6609375_latest.zip -d $ANDROID_HOME/cmdline-tools
        echo "export ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
        echo "export PATH=$ANDROID_HOME/cmdline-tools/tools/bin:$PATH" >> $GITHUB_ENV
        echo "export PATH=$ANDROID_HOME/platform-tools:$PATH" >> $GITHUB_ENV
        yes | sdkmanager --licenses
        sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.2"

    - name: Build APK
      run: |
        cd www
        cordova build android --release -- --keystore=path/to/keystore --storePassword=keystore_password --alias=key_alias --password=key_password
      env:
        ANDROID_HOME: ${{ secrets.ANDROID_HOME }}

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: my-app-apk
        path: platforms/android/app/build/outputs/apk/release/app-release.apk
